export const servicesData = [
  {
    id: "holdings",
    name: "PrimeBridge Holdings (Pvt) Ltd",
    description:
      "The parent company and strategic umbrella of the PrimeBridge Group of Companies. Overseeing corporate governance, group strategy, and inter-company alignment across all divisions.",
    icon: "Building2",
    services: [],
  },
  {
    id: "corporate-services",
    name: "PrimeBridge Corporate Services (Pvt) Ltd",
    description: "A professional financial and corporate advisory arm delivering comprehensive business support services. Ensures full financial compliance and operational efficiency for businesses.",
    icon: "Briefcase",
    services: [
      {
        id: "accounting",
        name: "Accounting & Bookkeeping",
        desc: "Accurate, timely, and well-organised financial records.",
        pricingType: "starting",
        startingFrom: "LKR 20,000",
        pricingNote: "per month",
        included: [
          "Monthly bookkeeping & ledger maintenance",
          "Bank reconciliation",
          "Financial statements preparation",
          "Accounts payable & receivable management",
          "Dedicated accountant assigned to your business",
        ],
      },
      {
        id: "financial-advisory",
        name: "Financial & Business Advisory",
        desc: "Financial planning, cash flow management, and investment appraisals.",
        pricingType: "tiered",
        pricingTiers: [
          {
            label: "Retainer Basis",
            price: "LKR 8,000",
            period: "per month",
            note: "Ongoing monthly advisory retainer",
          },
          {
            label: "Scenario Basis",
            price: "Custom",
            period: null,
            note: "Quoted per scenario or engagement",
            isDM: true,
          },
        ],
        included: [
          "Financial planning & budgeting",
          "Cash flow management & forecasting",
          "Investment appraisal & analysis",
          "Business performance review",
          "Strategic financial recommendations",
        ],
      },
      {
        id: "corporate-tax",
        name: "Corporate Tax Services",
        desc: "Tax planning, filing, and compliance for businesses.",
        pricingType: "starting",
        startingFrom: "LKR 25,000",
        pricingNote: "per annum",
        pricingDetails:
          "Minimum package. Final pricing depends on the nature and size of the company.",
        included: [
          "Corporate income tax return preparation & filing",
          "Tax planning & liability minimisation",
          "IRD compliance & deadline management",
          "VAT / NBT registration and returns (where applicable)",
          "Liaison with the Inland Revenue Department",
        ],
      },
      {
        id: "individual-tax",
        name: "Individual Tax Services",
        desc: "Income tax registration, annual returns, and personal tax planning.",
        pricingType: "categories",
        categories: [
          {
            label: "Corporate Employees",
            price: "LKR 10,000",
            period: "per annum",
          },
          {
            label: "Freelancers / Resident Foreign Income Earners",
            price: "LKR 20,000",
            period: "per annum",
          },
        ],
        included: [
          "Income tax registration with the IRD",
          "Annual income tax return preparation & filing",
          "Personal tax planning & advisory",
          "Assessment of resident foreign income obligations",
          "IRD correspondence & compliance support",
        ],
      },
      {
        id: "company-registration",
        name: "Company Registration",
        desc: "Complete company registration process with the Registrar of Companies.",
        pricingType: "packages",
        packages: [
          {
            name: "Basic",
            price: "LKR 15,000",
            period: "one-time",
            highlight: false,
            features: [
              "Private limited company registration",
              "Name reservation & approval",
              "Submission to Registrar of Companies",
              "Certificate of incorporation",
            ],
          },
          {
            name: "Standard",
            price: "LKR 25,000",
            period: "one-time",
            highlight: true,
            badge: "Most Popular",
            features: [
              "Everything in Basic",
              "Article of association drafting",
              "Share structure setup",
              "Director & shareholder registration",
              "Registered office address setup",
            ],
          },
          {
            name: "Premium",
            price: "LKR 40,000",
            period: "one-time",
            highlight: false,
            features: [
              "Everything in Standard",
              "Tax registration (IRD)",
              "Opening bank account guidance",
              "Company secretary appointment",
              "Post-incorporation compliance checklist",
            ],
          },
        ],
        included: [
          "End-to-end registration handling",
          "Document preparation & submission",
          "Liaison with Registrar of Companies",
          "Certificate of incorporation",
          "Dedicated point of contact throughout",
        ],
      },
      {
        id: "company-secretarial",
        name: "Company Secretarial Services",
        desc: "Post-incorporation statutory and regulatory compliance.",
        pricingType: "dm",
        dmText: "Pricing depends on scope of secretarial services required.",
      },
    ],
  },
  {
    id: "solutions",
    name: "PrimeBridge Solutions (Pvt) Ltd",
    description:
      "A technology and digital services company helping businesses establish and grow their digital presence. Empowers businesses with modern digital tools and strategies.",
    icon: "MonitorPlay",
    services: [
      {
        id: "social-media",
        name: "Social Media Management",
        desc: "Create, schedule, and manage engaging content across platforms.",
        pricingType: "packages",
        packages: [
          {
            name: "Starter",
            price: "LKR 30,000",
            period: "per month",
            highlight: false,
            features: [
              "6 Posts per month",
              "Weekly product highlights",
              "Simple Promo / CTA Posts",
            ],
          },
          {
            name: "Growth",
            price: "LKR 52,000",
            period: "per month",
            highlight: true,
            badge: "Most Popular",
            features: [
              "8 Posts + 2 Reels (30s) per month",
              "Weekly product highlights",
              "Simple Promo / CTA Posts",
              "Promo Sequences",
              "Product Reels",
            ],
          },
          {
            name: "Premium",
            price: "LKR 85,000",
            period: "per month",
            highlight: false,
            features: [
              "10 Posts + 4 Reels (30s) per month",
              "Strong Reel frequency",
              "Campaign style monthly promo plan",
            ],
          },
        ],
        addons: [
          { label: "Additional Static Post", price: "LKR 3,500" },
          { label: "Additional Carousel", price: "LKR 7,000" },
          { label: "Reel (max 30s)", price: "LKR 10,000" },
          { label: "Reel (max 60s)", price: "LKR 13,500" },
          { label: "Story", price: "LKR 2,000" },
          {
            label: "Photography / Special Promotions",
            price: "Quoted separately",
            isNote: true,
          },
        ],
        included: [
          "Content creation & copywriting",
          "Post scheduling & publishing",
          "Platform management (Instagram, Facebook & LinkedIn)",
          "Monthly content calendar",
          "Performance reporting",
        ],
      },
      {
        id: "digital-marketing",
        name: "Digital Marketing",
        desc: "SEO, PPC, and email campaigns designed to grow visibility.",
        pricingType: "dm",
        dmText: "Pricing depends on channels and campaign scope.",
      },
      {
        id: "graphic-design",
        name: "Graphic Design & Branding",
        desc: "Logos, brand identities, and marketing materials.",
        pricingType: "dm",
        dmText: "DM us with your requirements for a custom quote.",
      },
      {
        id: "web-development",
        name: "Website Development",
        desc: "Modern, responsive websites and web applications.",
        pricingType: "dm",
        dmText: "DM us with your requirements for a custom quote.",
      },
      {
        id: "domain-setup",
        name: "Domain Registration & Setup",
        desc: "Sourcing, purchasing, and configuring your domain.",
        pricingType: "starting",
        startingFrom: "LKR 12,000",
        pricingNote: "per annum",
        pricingDetails: "Terms & Conditions apply. Bundled with email setup available.",
        included: [
          "Domain name sourcing & registration",
          "DNS configuration & setup",
          "Domain renewal management",
          "Technical support during setup",
          "Bundled email setup available",
        ],
      },
      {
        id: "email-setup",
        name: "Business Email Setup",
        desc: "Professional email accounts configured for your team.",
        pricingType: "starting",
        startingFrom: "LKR 12,000",
        pricingNote: "per annum",
        pricingDetails:
          "Bundled domain & email setup available. Terms & Conditions apply.",
        included: [
          "Professional business email accounts",
          "Email hosting configuration",
          "Team account setup & management",
          "Email client configuration support",
          "Bundled domain registration available",
        ],
      },
      {
        id: "it-support",
        name: "IT Support & Hardware Solutions",
        desc: "Procurement, setup, and maintenance of IT hardware.",
        pricingType: "dm",
        dmText: "DM us with your hardware requirements for a quote.",
      },
    ],
  },
  {
    id: "talent-management",
    name: "PrimeBridge Talent Management (Pvt) Ltd",
    description:
      "A human resource solutions provider focused on building and managing high-performing teams. Delivers efficient and scalable workforce solutions.",
    icon: "Users",
    services: [
      {
        id: "hr-outsourcing",
        name: "HR Outsourcing",
        desc: "Complete, professional HR function without the overhead.",
        pricingType: "dm",
        dmText: "Price depends on the scenario. DM us for a quotation.",
      },
      {
        id: "recruitment",
        name: "Recruitment & Headhunting",
        desc: "Proactively identifying and engaging top-tier candidates.",
        pricingType: "recruitment-tiers",
        recruitmentTiers: [
          {
            tier: "Tier 1",
            label: "Operational & Non-Executive",
            description:
              "Administrative, clerical, junior and support-level positions",
            fee: "LKR 30,000",
            feeType: "Fixed fee per placement",
            guarantee: "30-day replacement guarantee",
            highlight: false,
          },
          {
            tier: "Tier 2",
            label: "Executive to Assistant Manager",
            description:
              "Executive, senior executive and assistant managerial positions",
            fee: "5%",
            feeType: "of annual gross remuneration",
            guarantee: "45-day replacement guarantee",
            highlight: false,
          },
          {
            tier: "Tier 3",
            label: "Managerial & Senior Roles",
            description:
              "Managerial, senior management and leadership positions",
            fee: "8% – 10%",
            feeType: "Varies by seniority & search complexity",
            guarantee: "60–90 day replacement guarantee",
            highlight: true,
            badge: "Most Requested",
          },
          {
            tier: "Tier 4",
            label: "Specialized Roles",
            description:
              "Industry-specific or client-tailored senior and leadership mandates",
            fee: "15%",
            feeType: "of annual gross remuneration",
            guarantee: "60–90 day replacement guarantee",
            highlight: false,
          },
        ],
        paymentNote:
          "Fees are earned upon the candidate's written acceptance of the employment offer. Invoice payable within 7 days.",
        cancellationNote:
          "Role cancellation fee applies if a role is withdrawn after sourcing has commenced: LKR 10,000 for operational roles; 15% of fee for executive and above.",
        guaranteeDisclaimer:
          "The replacement guarantee does not apply where departure arises from changes to the agreed role, company restructuring, salary disputes not disclosed at offer stage, or workplace culture issues. No cash refunds are issued under any circumstances.",
        included: [
          "Role briefing & job description development",
          "Candidate sourcing & headhunting",
          "CV screening & shortlisting",
          "Interview coordination & scheduling",
          "Offer management & placement support",
          "Replacement guarantee per tier",
        ],
      },
      {
        id: "payroll",
        name: "Payroll Management",
        desc: "End-to-end payroll processing including statutory deductions.",
        pricingType: "dm",
        dmText: "Price depends on the scenario. DM us for a quotation.",
      },
      {
        id: "staff-placement",
        name: "Full-Time Staff Placement",
        desc: "Sourcing and placing qualified professionals.",
        pricingType: "dm",
        dmText: "Price depends on the scenario. DM us for a quotation.",
      },
    ],
  },
];